### PR TITLE
New Functionality

### PR DESCRIPTION
**Pull request by aflick2486**
Added the ability to search by confidence, provider, tags, group, or day.
Added ability to set your own provider in the settings page.
Also added confidence numbers to the levels to make it more readable on the submit page.

### CODE REVIEW

**Comment by wesyoung** [comment]
awesome thanks! i'll try to test out a bit and get it into the chrome store soon...

**Comment by aflick2486** [comment]
No problem!

**Comment by coonsmatthew** [comment]
@wesyoung I'm curious if this has been updated on the Chrome store yet? 

Thanks!

**Comment by wesyoung** [comment]
just pushed. give it ~60min to propagate. wanted to spend some time looking through the changes since there were quite a bit... great job @aflick2486! looks good! :)

**Comment by wesyoung** [comment]
the ver is 2.0.8

**Comment by coonsmatthew** [comment]
Awesome, I see the updated version now. Thanks Wes!

**Pull request merged**
